<?php echo $this->doctype(); ?>

<!-- Signup layout -->
<html lang="en">
	<head>
		<?php echo $this->headTitle(); ?>
		
    	
		<!-- Meta -->
		<?php echo $this->headMeta(); ?>
		

		<!-- Styles -->
		<?php echo $this->headLink(); ?>
		

		<!-- Head Scripts -->
		<?php echo $this->headScript(); ?>
		

	</head>
	<body>
		<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
			</div>
			<div class="navbar-collapse">
				<a class="btn btn-primary navbar-btn navbar-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
				<a class="btn btn-success navbar-btn navbar-right" href="<?php echo $this->url('signup/plan', array('plan'=>'free')); ?>">Sign up for free</a>
			</div>
		</nav>
		
		<?php echo $this->content; ?>

		<div class="container">
			<footer>
				<p class="pull-right"><a href="#">Back to top</a></p>
				<ul class="list-inline">
					<li><a href="<?php echo $this->url('about'); ?>"><?php echo $this->translate('About'); ?></a></li>
					<li><a href="<?php echo $this->url('help'); ?>"><?php echo $this->translate('Help'); ?></a></li>
					<li><a href="<?php echo $this->url('terms'); ?>"><?php echo $this->translate('Terms of Use'); ?></a></li>
					<li><a href="<?php echo $this->url('privacy'); ?>"><?php echo $this->translate('Privacy'); ?></a></li>
					<li>&copy; 2005 - <?php echo date('Y') ?> <a href="http://omelett.es">Omelett.es Ltd</a>.</li>
				</ul>
			</footer>
		</div>
        
		<!-- Document End Scripts -->
		<?php echo $this->inlineScript(); ?>
        
    </body>
</html>
