<?php echo $this->doctype(); ?>

<!-- Signup layout -->
<html lang="en">
    <head>
    	<?php echo $this->headTitle($this->translate('Quantum 2'))->setSeparator(' - ')->setAutoEscape(false) ?>
    	
    	<!-- Meta -->
        <?php
        	echo $this->headMeta()
        		->setCharset('utf-8')
        		->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>

        <!-- Styles -->
        <?php
        	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
        		->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        		->appendStylesheet($this->basePath() . '/css/quantum.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    	<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
        	</div>
        	<div class="navbar-collapse">
        		<a class="btn btn-primary navbar-btn navbar-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
        	</div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="http://omelett.es">Omelett.es Ltd</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
