<?php echo $this->doctype(); ?>

<!-- Signup layout -->
<html lang="en">
    <head>
    	<?php echo $this->headTitle(); ?>
    	
    	<!-- Meta -->
        <?php echo $this->headMeta(); ?>

        <!-- Styles -->
        <?php echo $this->headLink(); ?>

        <!-- Scripts -->
        <?php echo $this->headScript(); ?>

    </head>
    <body>
    	<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
        	</div>
        	<div class="navbar-collapse">
        		<a class="btn btn-primary navbar-btn navbar-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
        	</div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="http://omelett.es">Omelett.es Ltd</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
