<?php echo $this->doctype(); ?>

<!-- Signup layout -->
<html lang="en">
	<?php echo $this->partial('partial/signup-head.phtml'); ?>
	
	<body>
		<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
			</div>
			<div class="navbar-collapse">
				<a class="btn btn-primary navbar-btn navbar-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
			</div>
		</nav>
		
		<?php echo $this->content; ?>

		<!-- Document End Scripts -->
		<?php echo $this->inlineScript(); ?>
        
    </body>
</html>
