<?php echo $this->doctype(); ?>

<!-- Auth layout -->
<html lang="en">
	<head>
		<?php echo $this->headTitle(); ?>
			
	    	
		<!-- Meta -->
		<?php echo $this->headMeta(); ?>
			
	
		<!-- Styles -->
		<?php echo $this->headLink(); ?>
			
	
		<!-- Head Scripts -->
		<?php echo $this->headScript(); ?>
			
	
	</head>
    <body>
    	<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
        	</div>
        </nav>
        <div class="container">
        	<?php foreach ($this->flashMessenger('success') as $message): ?>
        	<div class="alert alert-success">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        	<?php foreach ($this->flashMessenger('error') as $message): ?>
        	<div class="alert alert-danger">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        	
        	<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="http://omelett.es">Omelett.es Ltd</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
