<footer class="container">
	<p class="pull-right"><a href="#">Back to top</a></p>
	<ul class="list-inline">
		<li><a href="<?php echo $this->url('about'); ?>"><?php echo $this->translate('About'); ?></a></li>
		<li><a href="<?php echo $this->url('help'); ?>"><?php echo $this->translate('Help'); ?></a></li>
		<li><a href="<?php echo $this->url('terms'); ?>"><?php echo $this->translate('Terms of Use'); ?></a></li>
		<li><a href="<?php echo $this->url('privacy'); ?>"><?php echo $this->translate('Privacy'); ?></a></li>
		<li>&copy; 2005 - <?php echo date('Y') ?> <a href="http://omelett.es">Omelett.es Ltd</a>.</li>
	</ul>
</footer>
