<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Quantum 2'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
        	</div>
        	<?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
        	
        	<?php if ($this->userLogin()->hasIdentity()): ?>
        	<ul class="nav navbar-nav navbar-right">
        		<li class="dropdown">
        			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->escapeHtml($this->userLogin()->getIdentity()->fullName); ?> <b class="caret"></b></a>
        			<ul class="dropdown-menu">
        				<li><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Log out'); ?></a></li>
        			</ul>
        		</li>
        	</ul>
        	<?php else: ?>
        	<a class="btn btn-primary navbar-btn pull-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
        	<?php endif; ?>
        </nav>
        <div class="container">
        	<?php foreach ($this->flashMessenger('success') as $message): ?>
        	<div class="alert alert-success">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        	<?php foreach ($this->flashMessenger('error') as $message): ?>
        	<div class="alert alert-danger">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="http://omelett.es">Omelett.es Ltd</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
