<?php echo $this->doctype(); ?>

<!-- Default layout -->
<html lang="en">
	<head>
		<?php echo $this->headTitle(); ?>
			
	    	
		<!-- Meta -->
		<?php echo $this->headMeta(); ?>
			
	
		<!-- Styles -->
		<?php echo $this->headLink(); ?>
			
	
		<!-- Head Scripts -->
		<?php echo $this->headScript(); ?>
			
	
	</head>
    <body>
        <nav class="navbar navbar-static-top navbar-inverse" role="navigation">
        	<div class="navbar-header">
        		<a class="navbar-brand" href="/"><?php echo $this->translate('Quantum 2'); ?></a>
        	</div>
        	<?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
        	
        	<div class="navbar-collapse">
	        	<?php if ($this->userLogin()->hasIdentity()): ?>
	        	<ul class="nav navbar-nav navbar-right">
	        		<li class="dropdown">
	        			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $this->escapeHtml($this->userLogin()->getIdentity()->fullName); ?> <b class="caret"></b></a>
	        			<ul class="dropdown-menu">
	        				<?php if ($this->userLogin()->getIdentity()->admin): ?>
	        				<li><a href="<?php echo $this->url('admin'); ?>"><?php echo $this->translate('Admin'); ?></a></li>
	        				<?php endif; ?>
	        				<li><a href="<?php echo $this->url('preferences'); ?>"><span class="glyphicon glyphicon-wrench"></span> <?php echo $this->translate('User Preferences'); ?></a></li>
	        				<li><a href="<?php echo $this->url('logout'); ?>"><span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Log out'); ?></a></li>
	        			</ul>
	        		</li>
	        	</ul>
	        	<?php else: ?>
	        	<a class="btn btn-primary navbar-btn pull-right" href="<?php echo $this->url('login'); ?>">Sign in</a>
	        	<?php endif; ?>
        	</div>
        </nav>
        <div class="container">
        	<?php foreach ($this->flashMessenger('success') as $message): ?>
        	<div class="alert alert-success">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        	<?php foreach ($this->flashMessenger('error') as $message): ?>
        	<div class="alert alert-danger">
        		<button type="button" class="close" data-dismiss="alert">&times;</button>
        		<?php echo $this->escapeHtml($message); ?>
        	</div>
        	<?php endforeach; ?>
        
            <?php echo $this->content; ?>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="http://omelett.es">Omelett.es Ltd</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
