<div class="carousel slide" id="carousel-features">
	<ol class="carousel-indicators">
		<li data-target="#carousel-features" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-features" data-slide-to="1"></li>
		<li data-target="#carousel-features" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="item active">
			<div class="container">
				<div class="carousel-caption">
					<h2>Example Headline</h2>
					<p>Some interesting text.</p>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="container">
				<div class="carousel-caption">
					<h2>Another Example Headline</h2>
					<p>Blah, blah, blah.</p>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="container">
				<div class="carousel-caption">
					<h2>Yet Another Example Headline</h2>
					<p>Lorem ipsum dolurum est factum ecetera ecetera.</p>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#carousel-features" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href="#carousel-features" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>

<div class="container thewhys">
	<div class="row">
		<div class="col-lg-4">
			<h2>Yes</h2>
			<p>There are some good stuffs here.</p>
		</div>
		<div class="col-lg-4">
			<h2>Very Yes</h2>
			<p>Aint go no time for no troublemakers.</p>
		</div>
		<div class="col-lg-4">
			<h2>Word to Your Mother</h2>
			<p>Indeed.</p>
		</div>
	</div>
</div>

<div class="container featurettes">

</div>
