<div class="carousel slide" id="carousel-features">
	<ol class="carousel-indicators">
		<li data-target="#carousel-features" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-features" data-slide-to="1"></li>
		<li data-target="#carousel-features" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="item active">
			<img data-src="/js/holder.js/100%x500/auto/#777:#888/text:This is some text">
			<div class="carousel-caption">One</div>
		</div>
		<div class="item">
			<img data-src="/js/holder.js/100%x500/auto/#333:#444/text:I like cheese">
			<div class="carousel-caption">Two</div>
		</div>
		<div class="item">
			<img data-src="/js/holder.js/100%x500/auto/#ccc:#ddd/text:Shut the door">
			<div class="carousel-caption">Three</div>
		</div>
	</div>
	<a class="left carousel-control" href="#carousel-features" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href="#carousel-features" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
