<h2><?php echo $this->translate('Users'); ?></h2>
<div class="panel panel-info">
	<div class="panel-heading">Help</div>
	<div class="panel-body">Users are great</div>
</div>

<?php echo $this->tabulate($this->users); ?>

<!--
<table class="table table-hover">
	<thead>
		<tr>
			<th>Username</th>
			<th>Full Name</th>
			<th>Admin?</th>
		</tr>
	</thead>
	<tbody>
		<?php if (count($this->users) > 0): ?>
		<?php foreach ($this->users as $user): ?>
		<tr>
			<td><img class="img-rounded" src="http://www.gravatar.com/avatar/<?php echo md5($user->name); ?>?s=40"> <?php echo $this->escapehtml($user->name); ?></td>
			<td><?php echo $this->escapehtml($user->fullName); ?></td>
			<td><?php echo $this->escapehtml($user->admin); ?></td>
		</tr>
		<?php endforeach; ?>
		<?php else: ?>
		<tr>
			<td>No results</td>
		</tr>
		<?php endif; ?>
	</tbody>
</table>
-->
