<div class="row">
	<div class="col-lg-4 col-lg-offset-4">
		<h2><?php echo $this->translate('Sign in to'); ?> <?php echo $this->translate('Quantum 2'); ?></h2>
		<?php echo $this->partial('partial/form/friendly.phtml', array('form' => $this->form)); ?>
		<p class="text-center"><a href="<?php echo $this->url('forgot-password'); ?>"><?php echo $this->translate('Forgot password?'); ?></a></p>
		<p class="text-center"><?php echo $this->translate("Don't have an account?");?> <a href="<?php echo $this->url('signup'); ?>"><?php echo $this->translate('Sign up for free today!'); ?></a></p>
	</div>
</div>
